# Generated by Django 5.2.1 on 2025-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('adress', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
